// Package report renders the two key deliverables: a pre-formatted carrier
// complaint (运营商申诉报告) and a fully self-contained static HTML report that
// opens in any browser with no server and no network access.
package report

import (
	"fmt"
	"io"
	"strings"
	"time"

	"github.com/wangzi5151/nethole-tester/internal/analyze"
)

// Meta carries the optional identity fields printed on a complaint report.
type Meta struct {
	Operator    string
	Account     string
	Contact     string
	Location    string
	GeneratedAt time.Time
}

// WriteComplaint writes a ready-to-screenshot broadband complaint report.
func WriteComplaint(w io.Writer, a *analyze.Analysis, meta Meta) {
	if meta.GeneratedAt.IsZero() {
		meta.GeneratedAt = time.Now()
	}
	op := meta.Operator
	if op == "" {
		op = "________________"
	}

	fmt.Fprintln(w, "================================================================")
	fmt.Fprintln(w, "        宽带网络质量申诉报告 / Broadband Quality Complaint")
	fmt.Fprintln(w, "              由 NetHole-Tester 自动生成 / generated by NetHole-Tester")
	fmt.Fprintln(w, "================================================================")
	fmt.Fprintf(w, " 运营商 Operator : %s\n", op)
	fmt.Fprintf(w, " 宽带账号 Account: %s\n", orDash(meta.Account))
	fmt.Fprintf(w, " 联系电话 Contact: %s\n", orDash(meta.Contact))
	fmt.Fprintf(w, " 装机地址 Address: %s\n", orDash(meta.Location))
	fmt.Fprintf(w, " 生成时间 Created: %s\n", meta.GeneratedAt.Format("2006-01-02 15:04:05"))
	fmt.Fprintln(w)
	fmt.Fprintln(w, "【一、问题描述 / Problem statement】")
	fmt.Fprintln(w, "  本人网络频繁出现“看似连接正常但随机卡顿 1~3 秒”的现象。")
	fmt.Fprintln(w, "  普通测速显示正常，但实际使用中会突然断流、丢包、延迟暴涨。")
	fmt.Fprintln(w, "  以下数据为在本机持续主动探测所得，非测速峰值截图。")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "【二、客观数据 / Objective measurements】")
	fmt.Fprintf(w, "  监控时段 Period : %s ~ %s\n", a.Start.Format("2006-01-02 15:04:05"), a.End.Format("2006-01-02 15:04:05"))
	fmt.Fprintf(w, "  监控时长 Duration: %s\n", a.Duration.Round(time.Second))
	fmt.Fprintf(w, "  采样总数 Samples : %d\n", a.TotalSamples)
	fmt.Fprintf(w, "  异常事件 Holes   : %d 次，累计异常 %s\n", len(a.Events), a.HoleDuration.Round(time.Second))
	fmt.Fprintln(w)

	for _, k := range analyze.SortedKinds(a.Kinds) {
		ks := a.Kinds[k]
		fmt.Fprintf(w, "  · %-10s 丢包 %.2f%% (%d/%d)  平均 %.1fms  p95 %.1fms  p99 %.1fms  最大 %.1fms\n",
			k.Label(), ks.LossPct, ks.Loss, ks.Total, ks.AvgMs, ks.P95Ms, ks.P99Ms, ks.MaxMs)
	}
	fmt.Fprintln(w)

	fmt.Fprintln(w, "【三、异常时间轴 / Event timeline】")
	if len(a.Events) == 0 {
		fmt.Fprintln(w, "  本次监控未捕获到达到阈值的异常事件。")
	} else {
		fmt.Fprintln(w, "  序号   开始时间        持续      类型       严重度   说明")
		for i, e := range a.Events {
			fmt.Fprintf(w, "  #%-4d %s  %6.2fs  %-9s %-8s %s\n",
				i+1, e.Start.Format("15:04:05"), e.Duration().Seconds(), e.Kind.Label(), e.Severity, e.Reason)
		}
	}
	fmt.Fprintln(w)

	// Evidence snapshots for up to 3 events.
	shown := 0
	for _, e := range a.Events {
		if e.Snapshot == nil || shown >= 3 {
			continue
		}
		shown++
		fmt.Fprintf(w, "【证据快照 #%d / Evidence @ %s】\n", shown, e.Start.Format("2006-01-02 15:04:05"))
		if e.Snapshot.Traceroute != "" {
			fmt.Fprintln(w, "  -- 路由追踪 traceroute --")
			indentLines(w, e.Snapshot.Traceroute, "    ")
		}
		if len(e.Snapshot.DNS) > 0 {
			fmt.Fprintln(w, "  -- 当时 DNS 解析 --")
			for q, ans := range e.Snapshot.DNS {
				fmt.Fprintf(w, "    %s = %s\n", q, ans)
			}
		}
		if e.Snapshot.Wifi != "" {
			fmt.Fprintln(w, "  -- Wi-Fi 信号 --")
			indentLines(w, firstLines(e.Snapshot.Wifi, 6), "    ")
		}
		if e.Snapshot.ARP != "" {
			fmt.Fprintln(w, "  -- 局域网 ARP 表 --")
			indentLines(w, firstLines(e.Snapshot.ARP, 6), "    ")
		}
		fmt.Fprintln(w)
	}

	fmt.Fprintln(w, "【四、建议话术 / Suggested script】")
	fmt.Fprintln(w, "  “您好，我的宽带到户速率正常，但存在周期性丢包与延迟突增，")
	fmt.Fprintln(w, "   已用 NetHole-Tester 记录了完整的毫秒级证据（见上方时间轴与快照）。")
	fmt.Fprintln(w, "   这属于上网质量不达标，请安排线路检测与光猫/端口排查，并登记工单。”")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "  若一线客服不处理，可要求转‘网络质量投诉’并保留本报告截图。")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "----------------------------------------------------------------")
	fmt.Fprintln(w, " 本报告全部在您的设备本地生成，未上传任何数据。")
	fmt.Fprintln(w, " This report was generated entirely on-device; nothing was uploaded.")
	fmt.Fprintln(w, "----------------------------------------------------------------")
}

// WriteText writes the standard local analysis (statistics + hints).
func WriteText(w io.Writer, a *analyze.Analysis) {
	analyze.RenderText(w, a)
	fmt.Fprintln(w, "-- 相关性线索 / Correlation clues (仅提示，非诊断) ------------")
	for i, h := range analyze.Hints(a) {
		fmt.Fprintf(w, "  %d) %s\n", i+1, h)
	}
	fmt.Fprintln(w)
}

func indentLines(w io.Writer, s, prefix string) {
	for _, ln := range strings.Split(s, "\n") {
		fmt.Fprintf(w, "%s%s\n", prefix, ln)
	}
}

func firstLines(s string, n int) string {
	lines := strings.Split(s, "\n")
	if len(lines) <= n {
		return s
	}
	return strings.Join(lines[:n], "\n") + "\n    ..."
}

func orDash(s string) string {
	if s == "" {
		return "________________"
	}
	return s
}
